--     ┏┏┓ o ┳━┓ ┓━┓ ┏┏┓ ┳━┓
--     ┃┃┃ ┃ ┃━┫ ┗━┓ ┃┃┃ ┃━┫
--     ┛ ┇ ┇ ┛ ┇ ━━┛ ┛ ┇ ┛ ┇
-- a fog descends upon your editor
-- https://github.com/xero/miasma.nvim

local colors = {
Normal = {fg = "#D7C483", bg = "#222222"},
FzfLuaBorder = {link = "Normal"},
FzfLuaNormal = {link = "Normal"},
NvimSpacing = {link = "Normal"},
javaScript = {link = "Normal"},
lessVariableValue = {link = "Normal"},
Boolean = {fg = "#78834b"},
["@boolean"] = {link = "Boolean"},
ColorColumn = {bg = "#222222"},
Comment = {fg = "#666666"},
CtrlPLinePre = {link = "Comment"},
LspCodeLens = {link = "Comment"},
NERDTreeHelp = {link = "Comment"},
helpSectionDelim = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Constant = {fg = "#bb7744"},
Character = {link = "Constant"},
rubyConstant = {link = "Constant"},
vimHiAttrib = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
Cursor = {fg = "#222222", bg = "#685742"},
FzfLuaCursor = {link = "Cursor"},
CursorColumn = {bg = "#1c1c1c"},
CursorLine = {bg = "#1c1c1c"},
FzfLuaCursorLine = {link = "CursorLine"},
CursorLineNr = {fg = "#78824b", bg = "#1c1c1c", bold = true},
FzfLuaCursorLineNr = {link = "CursorLineNr"},
Delimiter = {fg = "#d7c483"},
NvimArrow = {link = "Delimiter"},
NvimColon = {link = "Delimiter"},
NvimComma = {link = "Delimiter"},
NvimParenthesis = {link = "Delimiter"},
Operator = {link = "Delimiter"},
javaScriptBraces = {link = "Delimiter"},
markdownLinkDelimiter = {link = "Delimiter"},
markdownURLDelimiter = {link = "Delimiter"},
vimContinue = {link = "Delimiter"},
vimSetSep = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticDeprecated = {sp = "#685742", strikethrough = true},
DiagnosticError = {fg = "#b36d43"},
DiagnosticErrorFloating = {link = "DiagnosticError"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#5f875f"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticHintFloating = {fg = "#78824b"},
DiagnosticInfo = {fg = "#5f875f"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#78824b"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticSignError = {fg = "#b36d43", bg = "#1c1c1c"},
DiagnosticSignHint = {fg = "#5f875f", bg = "#1c1c1c"},
DiagnosticSignInfo = {fg = "#78824b", bg = "#1c1c1c"},
DiagnosticSignWarn = {fg = "#685742", bg = "#1c1c1c"},
DiagnosticUnderlineError = {underline = true},
DiagnosticUnderlineHint = {underline = true},
DiagnosticUnderlineInfo = {underline = true},
DiagnosticUnderlineOk = {underline = true},
DiagnosticUnderlineWarn = {underline = true},
DiagnosticUnnecessary = {fg = "#666666", underline = true},
DiagnosticVirtualTextError = {fg = "#b36d43"},
DiagnosticVirtualTextHint = {fg = "#78824b", bg = "#222222"},
DiagnosticVirtualTextInfo = {fg = "#78824b", bg = "#222222"},
DiagnosticVirtualTextWarn = {fg = "#685742", bg = "#222222"},
DiagnosticVirtualTextWarning = {fg = "#d7c483"},
DiagnosticWarn = {fg = "#685742"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticWarning = {fg = "#b36d43"},
DiagnosticFloatingWarning = {link = "DiagnosticWarning"},
DiagnosticWarningFloating = {fg = "#d7c483"},
DiffAdd = {fg = "#222222", bg = "#5f875f"},
["@text.diff.add"] = {link = "DiffAdd"},
DiffAdded = {fg = "#5f875f", bg = "#1c1c1c"},
DiffChange = {fg = "#222222", bg = "#685742"},
DiffDelete = {fg = "#222222", bg = "#b36d43", bold = true},
["@text.diff.delete"] = {link = "DiffDelete"},
DiffRemoved = {fg = "#b36d43", bg = "#1c1c1c"},
DiffText = {fg = "#222222", bg = "#c9a554", bold = true},
Directory = {fg = "#78824b", bg = "#1c1c1c"},
gitCommitFile = {link = "Directory"},
Error = {fg = "#c2c2b0", bg = "#bb7744"},
NvimInvalid = {link = "Error"},
ErrorMsg = {fg = "#b36d43", bg = "#222222"},
NvimInvalidSpacing = {link = "ErrorMsg"},
FloatShadow = {bg = "#101010"},
FloatShadowThrough = {bg = "#151515"},
FoldColumn = {fg = "#666666", bg = "#1c1c1c"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#b36d43", bg = "#1c1c1c"},
Function = {fg = "#78834b"},
["@function"] = {link = "Function"},
["@lsp.type.decorator"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#5f875f", bg = "#1c1c1c"},
GitSignsChange = {fg = "#685742", bg = "#1c1c1c"},
GitSignsDelete = {fg = "#b36d43", bg = "#1c1c1c"},
IblIndent = {fg = "#242d1d", nocombine = true},
IblScope = {fg = "#43492a", nocombine = true},
IblWhitespace = {fg = "#242d1d", nocombine = true},
Identifier = {fg = "#d7c483"},
NvimIdentifier = {link = "Identifier"},
rubyLocalVariableOrMethod = {link = "Identifier"},
["@field"] = {link = "Identifier"},
["@lsp.type.parameter"] = {link = "Identifier"},
["@lsp.type.property"] = {link = "Identifier"},
["@lsp.type.variable"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#444444", underline = true},
Conceal = {link = "Ignore"},
IncSearch = {fg = "#222222", bg = "#bb7744"},
FzfLuaSearch = {link = "IncSearch"},
Keyword = {fg = "#5f875f"},
PreProc = {link = "Keyword"},
["@keyword"] = {link = "Keyword"},
LazyButton = {bg = "#222222"},
LazyButtonActive = {fg = "#222222", bg = "#78834b"},
MasonHeaderSecondary = {link = "LazyButtonActive"},
MasonHighlightBlock = {link = "LazyButtonActive"},
MasonHighlightBlockBold = {link = "LazyButtonActive"},
LazyComment = {},
LazyCommit = {},
LazyCommitIssue = {},
LazyCommitScope = {},
LazyCommitType = {},
LazyDimmed = {},
LazyDir = {},
LazyH1 = {fg = "#78834b", bg = "#222222"},
LazyH2 = {fg = "#78834b", bg = "#222222"},
LazyLocal = {},
LazyNoCond = {},
LazyNormal = {bg = "#1c1c1c"},
LazyProgressDone = {},
LazyProgressTodo = {},
LazyProp = {},
LazyReasonCmd = {},
LazyReasonEvent = {},
LazyReasonFt = {},
LazyReasonImport = {},
LazyReasonKeys = {},
LazyReasonPlugin = {},
LazyReasonRuntime = {},
LazyReasonSource = {},
LazyReasonStart = {},
LazySpecial = {fg = "#c9a554"},
LazyTaskError = {},
LazyTaskOutput = {},
LazyUrl = {},
LazyValue = {},
LineNr = {fg = "#666666", bg = "#1c1c1c"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspBorderBG = {fg = "#685742", bg = "#222222"},
LspFloatWinNormal = {fg = "#d7c483", bg = "#43492a"},
LspReferenceRead = {fg = "#5f875f", sp = "#fd9720", bold = true, undercurl = true},
LspReferenceText = {fg = "#d7c483", bg = "#43492a", sp = "#fd9720", bold = true, undercurl = true},
LspReferenceWrite = {fg = "#5f875f", sp = "#fd9720", bold = true, undercurl = true},
LspSignatureActiveParameter = {sp = "#fbec9f", bold = true, italic = true, underline = true},
MasonError = {},
MasonHeader = {fg = "#d7c483", bg = "#1c1c1c"},
MasonHeading = {},
MasonHighlight = {fg = "#78824b", bg = "#222222"},
MasonMutedBlockBold = {link = "MasonHighlight"},
MasonHighlightBlockBoldSecondary = {},
MasonHighlightBlockSecondary = {},
MasonHighlightSecondary = {},
MasonMuted = {fg = "#c9a554", bg = "#1c1c1c"},
MasonMutedBlock = {link = "MasonMuted"},
MasonWarning = {},
MatchParen = {fg = "#d7c483", bold = true, underline = true},
ModeMsg = {bold = true},
MoreMsg = {fg = "#5f875f", bold = true},
NonText = {fg = "#666666", bold = true},
EndOfBuffer = {link = "NonText"},
Whitespace = {link = "NonText"},
markdownCodeDelimiter = {link = "NonText"},
markdownHeadingRule = {link = "NonText"},
Number = {fg = "#78824b"},
Float = {link = "Number"},
NvimNumber = {link = "Number"},
rubyInstanceVariable = {link = "Number"},
["@number"] = {link = "Number"},
NvimInternalError = {fg = "#1c1c1c", bg = "#b36d43"},
NvimFigureBrace = {link = "NvimInternalError"},
NvimInvalidSingleQuotedUnknownEscape = {link = "NvimInternalError"},
NvimSingleQuotedUnknownEscape = {link = "NvimInternalError"},
Pmenu = {fg = "#d7c483", bg = "#1c1c1c"},
NormalFloat = {link = "Pmenu"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#666666"},
FzfLuaScrollFloatEmpty = {link = "PmenuSbar"},
PmenuSel = {fg = "#222222", bg = "#78834b"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {fg = "#d7c483", bg = "#d7c483"},
FzfLuaScrollFloatFull = {link = "PmenuThumb"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#5f875f", bold = true},
RedrawDebugClear = {fg = "#222222", bg = "#c9a554"},
RedrawDebugComposed = {fg = "#222222", bg = "#78834b"},
RedrawDebugNormal = {reverse = true},
RedrawDebugRecompose = {fg = "#222222", bg = "#bb7744"},
ScrollbarCursor = {fg = "#222222"},
ScrollbarCursorHandle = {fg = "#222222", bg = "#1c1c1c", blend = 0},
ScrollbarError = {fg = "#685742"},
ScrollbarErrorHandle = {fg = "#685742", bg = "#1c1c1c", blend = 0},
ScrollbarGitAdd = {fg = "#5f875f"},
ScrollbarGitAddHandle = {fg = "#5f875f", bg = "#1c1c1c", blend = 0},
ScrollbarGitChange = {fg = "#685742"},
ScrollbarGitChangeHandle = {fg = "#685742", bg = "#1c1c1c", blend = 0},
ScrollbarGitDelete = {fg = "#b36d43"},
ScrollbarGitDeleteHandle = {fg = "#b36d43", bg = "#1c1c1c", blend = 0},
ScrollbarHandle = {bg = "#1c1c1c", blend = 0},
ScrollbarHint = {fg = "#5f875f"},
ScrollbarHintHandle = {fg = "#5f875f", bg = "#1c1c1c", blend = 0},
ScrollbarInfo = {fg = "#5f875f"},
ScrollbarInfoHandle = {fg = "#5f875f", bg = "#1c1c1c", blend = 0},
ScrollbarMisc = {fg = "#bb7744"},
ScrollbarMiscHandle = {fg = "#bb7744", bg = "#1c1c1c", blend = 0},
ScrollbarSearch = {fg = "#c9a554"},
ScrollbarSearchHandle = {fg = "#c9a554", bg = "#1c1c1c", blend = 0},
ScrollbarWarn = {fg = "#b36d43"},
ScrollbarWarnHandle = {fg = "#b36d43", bg = "#1c1c1c", blend = 0},
Search = {fg = "#222222", bg = "#5f875f"},
CurSearch = {link = "Search"},
QuickFixLine = {link = "Search"},
Substitute = {link = "Search"},
SignColumn = {fg = "#666666", bg = "#1c1c1c"},
CursorLineSign = {link = "SignColumn"},
Special = {fg = "#bb7744"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
TelescopeMatching = {link = "Special"},
TelescopeResultsFileIcon = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@constructor"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
SpecialKey = {fg = "#d7c483"},
SpellBad = {fg = "#685742", sp = "#d7c483", underline = true},
SpellCap = {fg = "#5f875f", sp = "#d7c483", underline = true},
SpellLocal = {fg = "#bb7744", sp = "#d7c483", underline = true},
SpellRare = {fg = "#b36d43", sp = "#d7c483", underline = true},
Statement = {fg = "#5f875f", bold = true},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
helpHyperTextEntry = {link = "Statement"},
phpDefine = {link = "Statement"},
rubyDefine = {link = "Statement"},
StatusLine = {fg = "#d7c483", bg = "#222222", bold = true},
MsgSeparator = {link = "StatusLine"},
StatusLineNC = {fg = "#666666", bg = "#222222", bold = true},
String = {fg = "#685742"},
CtrlPMatch = {link = "String"},
NERDTreeExecFile = {link = "String"},
NvimString = {link = "String"},
helpExample = {link = "String"},
markdownCodeBlock = {link = "String"},
phpHereDoc = {link = "String"},
["@string"] = {link = "String"},
SyntasticErrorSign = {fg = "#b36d43"},
SyntasticWarningSign = {fg = "#685742"},
TabLine = {fg = "#666666", bg = "#111111"},
TabLineFill = {fg = "#c9a554", bg = "#222222"},
TabLineSel = {fg = "#111111", bg = "#78834b", bold = true},
TabLineSelSep = {fg = "#78834b", bg = "#1c1c1c", bold = true},
TabLineSep = {fg = "#111111", bg = "#222222"},
TelescopeBorder = {fg = "#685742", bg = "#1c1c1c"},
TelescopePreviewBorder = {link = "TelescopeBorder"},
TelescopePromptCounter = {link = "TelescopeBorder"},
TelescopeResultsBorder = {link = "TelescopeBorder"},
TelescopeMultiIcon = {},
TelescopeMultiSelection = {},
TelescopeNormal = {},
TelescopePreviewBlock = {},
TelescopePreviewCharDev = {},
TelescopePreviewDate = {},
TelescopePreviewDirectory = {},
TelescopePreviewExecute = {},
TelescopePreviewGroup = {},
TelescopePreviewHyphen = {},
TelescopePreviewLink = {},
TelescopePreviewMatch = {},
TelescopePreviewMessage = {},
TelescopePreviewMessageFillchar = {},
TelescopePreviewNormal = {},
TelescopePreviewPipe = {},
TelescopePreviewRead = {},
TelescopePreviewSize = {},
TelescopePreviewSocket = {},
TelescopePreviewSticky = {},
TelescopePreviewUser = {},
TelescopePreviewWrite = {},
TelescopePromptBorder = {fg = "#b36d43", bg = "#1c1c1c"},
TelescopePromptNormal = {},
TelescopeResultsClass = {},
TelescopeResultsComment = {},
TelescopeResultsConstant = {},
TelescopeResultsDiffUntracked = {},
TelescopeResultsField = {},
TelescopeResultsFunction = {},
TelescopeResultsIdentifier = {},
TelescopeResultsLineNr = {},
TelescopeResultsMethod = {},
TelescopeResultsNormal = {},
TelescopeResultsNumber = {},
TelescopeResultsOperator = {},
TelescopeResultsSpecialComment = {},
TelescopeResultsStruct = {},
TelescopeResultsVariable = {},
TelescopePreviewLine = {link = "TelescopeSelection"},
TelescopeSelectionCaret = {fg = "#d7c483", bg = "#78824b"},
TelescopeTitle = {fg = "#5f875f", bg = "#1c1c1c"},
TelescopePreviewTitle = {link = "TelescopeTitle"},
TelescopePromptPrefix = {link = "TelescopeTitle"},
TelescopePromptTitle = {link = "TelescopeTitle"},
TelescopeResultsTitle = {link = "TelescopeTitle"},
TermCursor = {reverse = true},
Title = {fg = "#b36d43", bold = true},
FloatTitle = {link = "Title"},
helpHeadline = {link = "Title"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#d7c483", bold = true, underline = true},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#78834b", bold = true},
NvimNumberPrefix = {link = "Type"},
NvimOptionSigil = {link = "Type"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@type"] = {link = "Type"},
Underlined = {fg = "#78834b", underline = true},
helpHyperTextJump = {link = "Underlined"},
helpURL = {link = "Underlined"},
htmlLink = {link = "Underlined"},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
User1 = {fg = "#d7c483", bg = "#bb7744"},
User2 = {fg = "#d7c483", bg = "#666666"},
User3 = {fg = "#d7c483", bg = "#b36d43"},
User4 = {fg = "#d7c483", bg = "#222222"},
User5 = {fg = "#d7c483", bg = "#bb7744"},
User6 = {fg = "#d7c483", bg = "#c9a554"},
User7 = {fg = "#d7c483", bg = "#78824b"},
User8 = {fg = "#d7c483", bg = "#b36d43"},
User9 = {fg = "#d7c483", bg = "#666666"},
VertSplit = {fg = "#1c1c1c", bg = "#222222"},
WinSeparator = {link = "VertSplit"},
Visual = {fg = "#222222", bg = "#78824b"},
TelescopeSelection = {link = "Visual"},
WarningMsg = {fg = "#b36d43"},
WhichKey = {fg = "#d7c483", bg = "#1c1c1c"},
WhichKeyBorder = {bg = "#1c1c1c"},
WhichKeyDesc = {fg = "#5f875f", bg = "#1c1c1c"},
WhichKeyFloat = {bg = "#1c1c1c"},
WhichKeyGroup = {bg = "#1c1c1c"},
WhichKeySeparator = {fg = "#c9a554", bg = "#1c1c1c"},
WhichKeyValue = {fg = "#c9a554"},
WildMenu = {fg = "black", bg = "#c9a554"},
WinBar = {bold = true},
WinBarNC = {link = "WinBar"},
gitCommitBranch = {fg = "#b36d43"},
gitCommitSelectedFile = {fg = "#5f875f"},
gitCommitSelectedType = {fg = "#5f875f"},
gitCommitUnmergedFile = {fg = "#685742"},
gitCommitDiscardedFile = {link = "gitCommitUnmergedFile"},
gitCommitUntrackedFile = {link = "gitCommitUnmergedFile"},
gitCommitUnmergedType = {fg = "#685742"},
gitCommitDiscardedType = {link = "gitCommitUnmergedType"},
htmlArg = {fg = "#5f875f"},
htmlBold = {bold = true},
htmlBoldItalic = {bold = true, underline = true},
htmlBoldUnderline = {bold = true, underline = true},
htmlBoldUnderlineItalic = {bold = true, underline = true},
htmlH1 = {bold = true},
htmlItalic = {underline = true},
htmlTag = {fg = "#5f875f"},
htmlEndTag = {link = "htmlTag"},
htmlTagName = {fg = "#5f875f"},
htmlUnderline = {underline = true},
htmlUnderlineItalic = {underline = true},
lCursor = {fg = "bg", bg = "fg"},
lessVariable = {fg = "#b36d43"},
markdownBold = {bold = true},
markdownItalic = {underline = true},
mustacheMarker = {fg = "#bb7744"},
mustachePartial = {fg = "#bb7744"},
mustacheSection = {bold = true},
mustacheVariable = {fg = "#c9a554"},
mustacheVariableUnescape = {fg = "#685742"},
netrwClassify = {fg = "#666666", bold = true},
netrwExe = {fg = "#685742"},
phpIdentifier = {fg = "#b36d43"},
phpVarSelector = {link = "phpIdentifier"},
phpSpecialFunction = {fg = "#bb7744"},
shDerefSimple = {fg = "#b36d43"},
shDerefVar = {link = "shDerefSimple"},
xmlTag = {fg = "#78824b"},
xmlAttrib = {link = "xmlTag"},
xmlEndTag = {link = "xmlTag"},
xmlEqual = {link = "xmlTag"},
xmlTagName = {fg = "#78834b"},
xmlString = {link = "xmlTagName"},
}

vim.cmd("highlight clear")
vim.cmd("set background=dark")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='miasma'")
vim.cmd("let colors_name='miasma'")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
